# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=50)),
                ('deployer', models.CharField(max_length=20)),
                ('env', models.CharField(max_length=20)),
                ('tag_version', models.CharField(max_length=20, null=True)),
                ('running_status', models.IntegerField(default=0)),
                ('build_status', models.IntegerField(default=0)),
                ('deploy_status', models.IntegerField(default=0)),
                ('deploytime', models.DateTimeField(auto_now_add=True)),
                ('deploytime2', models.DateTimeField(auto_now=True)),
                ('branch_name', models.CharField(default='master', max_length=20)),
            ],
            options={
                'db_table': 'deploy',
                'ordering': ['appname'],
            },
        ),
    ]
